- menu_name: "Services"

- name: "My Services"
  url: "/services/"
  class: "services-link"
  title: "Services I can provide"

- name: "Get In Touch"
  url: "/contact/"
  class: "services-contact"
  title: "Contact"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "sitemap"
