- menu_name: "Services"

- name: "Consultancy: Rethink Your Club"
  url: "/sitemap.xml"
  class: "services-link"
  title: "Consultancy Services for Rotary Clubs"

- name: "Get In Touch"
  url: "/contact/"
  class: "email"
  title: "Contact"

- name: "Follow RethinkRotary on Twitter"
  url: http://twitter.com/RethinkRotary
  class: "Twitter-link"
  title: "Follow RethinkRotary on Twitter"


