- menu_name: "Quick Links"

- name: "Blog"
  url: "/blog/"
  title: "Blog"

- name: "Get In Touch"
  url: "/contact/"
  class: "services-contact"
  title: "Contact"

- name: "My Services"
  url: "/services/"
  class: "services-link"
  title: "Services I can provide"

- name: "Why Rethink Rotary"
  url: "/whyRethinkRotary/"
  title: "Why Rethink Rotary"


